---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 2.2
* from https://alexd106.github.io/intro2R/exercise_2.html
```{r myN, echo=FALSE, include=TRUE}
myNumber <- 12.43

# do some calculations
# natural log
log(myNumber)
```

```{r lg10, echo=TRUE, include=TRUE}
# log10
log10(myNumber)
```

```{r, echo=TRUE, include=TRUE}
log2(myNumber)
```
```{r, echo=TRUE, include=TRUE}
# squareroot
sqrt(myNumber)
```
```{r, echo=TRUE, include=TRUE}
# antilog
exp(myNumber)
```
## excercise 2.3
```{r, echo=TRUE, include=TRUE}
# area of circle

# Given diameter
diameter <- 20

# Calculate the radius
radius <- diameter / 2

# Calculate the area
area_circle <- pi * radius^2
```

# excercise 2.5&2.6
```{r, echo=TRUE, include=TRUE}
# creating vector
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)

# Calculate the mean
weight_mean <- mean(weight)

# Calculate variance
variance_weight <- var(weight)

# Calculate the standard deviation
sd_weight <- sd(weight)

# Calculate the range
range_weight <- range(weight)

# Calculate the number of elements in the vector
num_weights <- length(weight)

# Weight of first 5 children
first_five <- weight[1:5]
```

## excercise 2.7&2.8
```{r, echo=TRUE, include=TRUE}
# height of children
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
summary(height)
some_child <- height[c(2,3,9,10)]
shorter_child <- height [height <= 99]

#bmi of children
bmi <- weight/((height/100)^2)
```
## excercise 2.9
```{r, echo=TRUE, include=TRUE}
# creating sequence
seq1 <- seq(from = 0, to = 1, by = 0.1)
```

## excercise 2.10
```{r, echo=TRUE, include=TRUE}
# creating sequence 2
seq2 <- seq(from = 10, to = 1, by = -0.5)
```

## excercise 2.13
```{r, echo=TRUE, include=TRUE}
# childrens names
child_name <- c("Alfred", "Barbara", "James", "Jane", "John", "Judy", "Louise", "Mary", "Ronald", "William")
```

## excercise 2.14&2.15
```{r, echo=TRUE, include=TRUE}
# order of height (shortest to tallest)
height_ord <- order(height)
names_sort <- child_name [height_ord]

# order weight (heaviest to lightest)
weight_ord_rev <- rev(order(weight))
weight_rev <- child_name [weight_ord_rev]
```


# Session Information

```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
```


