---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 2
* from https://alexd106.github.io/intro2R/exercise_2.html

### Question 2

```{r myN, echo=TRUE, include=TRUE}
myNumber <- 12.43

# do some calculations
# natural log
log(myNumber)
```

```{r lg10, echo=TRUE, include=TRUE}
# log10
log10(myNumber)
```

```{r, echo=TRUE, include=TRUE}
log2(myNumber)
```
```{r sqrt, echo=TRUE, include=TRUE}
sqrt(myNumber)
```

```{r exp, echo=TRUE, include=TRUE}
exp(myNumber)
```
### Question 3

```{r, echo=TRUE, include=TRUE}
r <- 20
area_circle <- pi*r*r
print(area_circle)
```
Question 4
```{r, echo=TRUE, include=TRUE}
x <- 14* 0.51
x^(1/3)
print (x)
```
Question 5
```{r, echo=TRUE, include=TRUE}
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
```
Question 6
```{r, echo=TRUE, include=TRUE}
var (weight)
sd (weight)
range (weight)
length (weight)
first_5 <- weight [1:5]
```
Question 7
```{r, echo=TRUE, include=TRUE}
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
summary (height)
some_child <- height [c(2,3,9,10)]
shorter_child <- height [height <= 99]
```
Question 8
```{r, echo=TRUE, include=TRUE}
bmi <- weight/((height/100)^2)
print (bmi)
```
Question 9
```{r, echo=TRUE, include=TRUE}
seq1 <- seq(0, 1, by = 0.1)
print (seq1)
```
Question 10
```{r, echo=TRUE, include=TRUE}
seq2 <- seq(1, 10, by = 0.5)
seq2 <- rev(seq2)
print(seq2)
```

# Session Information
```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
```

