---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercise 4: Visualising data using base R and lattice graphics

## Exercise 4
* from https://alexd106.github.io/intro2R/exercise_2.html
```{r template_chunk., echo=TRUE, include=TRUE}
```

```{r 4., echo=TRUE, include=TRUE}
squid <- read.table(file = '/Users/tim/Library/CloudStorage/OneDrive-UniversiteitUtrecht/Documents/☆Academische Bestanden/☆Universiteit Utrecht/3e jaar Bachelor/(FA-CPS341) Omics in Oncology/repo_clone_group1/week2/data4exercises/squid1.txt', header = TRUE, sep = "\t", stringsAsFactors = TRUE)

squid$year_factor <- factor(squid$year) 
squid$month_factor <- factor(squid$month)
squid$maturity_factor <- factor(squid$maturity.stage)
#squid <- squid[, !(names(squid) %in% c("year", "month", "maturity.stage"))]

summary(squid)
str(squid)

```

```{r 5., echo=TRUE, include=TRUE}
xtabs(~ month_factor + year_factor, data = squid)
#xtabs is just faster to write when using more variables

#you can use a ftable when combining a contingency table with more than 2 variables, otherwise it will give multiple tables for the third variable.
ftable(xtabs(~ month_factor + year_factor + maturity_factor, data = squid))
```

```{r 9., echo=TRUE, include=TRUE}
plot(x = squid$DML, y = squid$weight)

squid$weight_log <- log(squid$weight)
squid$weight_sqrt <- sqrt(squid$weight)

plot(x = squid$DML, y = squid$weight_log)
plot(x = squid$DML, y = squid$weight_sqrt)

pdf(file = '/Users/tim/Library/CloudStorage/OneDrive-UniversiteitUtrecht/Documents/☆Academische Bestanden/☆Universiteit Utrecht/3e jaar Bachelor/(FA-CPS341) Omics in Oncology/repo_clone_group1/week2/exercises/squid_scatterplot_sqrt.pdf')
plot(x = squid$DML, y = squid$weight_sqrt)
dev.off()
```

```{r 10., echo=TRUE, include=TRUE}
boxplot(DML ~ maturity_factor, data = squid, ylab = "Dorsal Mantle Length", xlab = "maturity stage")

library(vioplot)
vioplot(DML ~ maturity_factor, data = squid, ylab = "Dorsal Mantle Length", xlab = "Maturity Stage", col = "lightblue")
```

```{r 12., echo=TRUE, include=TRUE}
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
    usr <- par("usr")
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = cex.cor * r)
}
panel.hist <- function(x, ...)
{
    usr <- par("usr")
    par(usr = c(usr[1:2], 0, 1.5) )
    h <- hist(x, plot = FALSE)
    breaks <- h$breaks; nB <- length(breaks)
    y <- h$counts; y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = "cyan", ...)
}
pairs(squid[, c("DML", "weight", "eviscerate.weight", "ovary.weight", "nid.length", "nid.weight")], lower.panel = panel.smooth, diag.panel = panel.hist, upper.panel = panel.cor)
```

# Session Information

```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
```


